### ISSUE TITLE
How to extract PaLM embeddings for code?

### ISSUE THREAD

**Issue by kb-open** [lucidrains/PaLM-pytorch#1]
Thanks for the work done! I have three questions.

1. How to get PaLM embeddings for Python code?
2. My downstream task is to classify Python functions in a file into different categories. Will it be possible to use PaLM embeddings directly and feed it into a simple machine learning classifier (e.g., SVC) to train it (i.e., without needing any fine-tuning of PaLM embeddings)? Or, would you suggest fine-tuning of the embeddings instead?
3. If you suggest fine-tuning instead, how to do that for PaLM?

**Comment by lucidrains** [comment]
@kb-open haha, this is only the neural network architecture, not the trained model - you'll need to get a lot of data, compute, and optimize what's in the repository for distributed efficient training - join eleuther.ai if you are interested in open sourced endeavors!
