### ISSUE TITLE
Encoder-Decoder-Model

### ISSUE THREAD

**Issue by Bachstelze** [lucidrains/PaLM-pytorch#15]
How can we make it to a full transformer architecture with encoder and decoder?
In [the follow-up paper "Scaling Instruction-Finetuned Language Models"](https://arxiv.org/pdf/2210.11416.pdf) they also used the t5 architecture and released only [those flan-t5 weights](https://huggingface.co/google/flan-t5-base).

**Comment by lucidrains** [comment]
done here https://github.com/lucidrains/PaLM-rlhf-pytorch/issues/6
