### ISSUE TITLE
triton, triton-transformer imcompatibility issue

### ISSUE THREAD

**Issue by jaes77** [lucidrains/PaLM-pytorch#8]
Thanks for the great 'pathways' model implementation.
I'm now trying to launch 'train.py' to check the example with your reference code.
When running train.py, an error pops up because pre-released triton version 0.2.0 is not compatible to triton-transformer released.
If triton is downgraded to the released version, there is no triton.language.constexpr and that triggers another error message in your code.
So far, I have no clue how to run the train.py code at all.
Any ideas or solutions to resolve this situation?

**Comment by kiritoD** [comment]
https://github.com/lucidrains/triton-transformer/blob/main/triton_transformer/utils.py
you can directly copy this function to your lib and it will work.
def calc_num_warps(block_size):
    num_warps = 4
    if block_size >= 2048:
        num_warps = 8
    if block_size >= 4096:
        num_warps = 16
    return num_warps

**Comment by jaes77** [comment]
It works well.
I appreciate it enormously. :)
